// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2025-2026 SKY, LLC.

//! The metadata table for `FieldId` — one `FieldMeta` per variant.
//!
//! Exception: single const fn match table; one arm per variant, cannot be
//! split without breaking the match expression.

use super::{
    AggregateMeta, Cardinality, FieldAccess, FieldId, FieldMeta, FieldType, SortDirection,
};

impl FieldId {
    /// Returns the metadata descriptor for this field variant.
    #[expect(
        clippy::too_many_lines,
        reason = "exhaustive field metadata match — one arm per FieldId variant"
    )]
    #[must_use]
    pub const fn metadata(self) -> FieldMeta {
        match self {
            Self::Drive => FieldMeta {
                id: self,
                canonical_name: "drive",
                aliases: &["drv"],
                field_type: FieldType::Enum,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Ascending),
                filterable: true,
                projectable: true,
                tui_label: "Drv",
                display_name: "Drive",
                df_column: "",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 26,
                },
            },
            Self::Path => FieldMeta {
                id: self,
                canonical_name: "path",
                aliases: &[],
                field_type: FieldType::String,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Ascending),
                filterable: true,
                projectable: true,
                tui_label: "Path",
                display_name: "Path",
                df_column: "path",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: false,
                    bucket_support: false,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Name => FieldMeta {
                id: self,
                canonical_name: "name",
                aliases: &[],
                field_type: FieldType::String,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Ascending),
                filterable: true,
                projectable: true,
                tui_label: "Name",
                display_name: "Name",
                df_column: "name",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Unbounded,
                    default_top: 100,
                },
            },
            Self::PathOnly => FieldMeta {
                id: self,
                canonical_name: "path_only",
                aliases: &["pathonly", "path only"],
                field_type: FieldType::String,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Ascending),
                filterable: true,
                projectable: true,
                tui_label: "Dir",
                display_name: "Path Only",
                df_column: "path_only",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Unbounded,
                    default_top: 30,
                },
            },
            Self::Size => FieldMeta {
                id: self,
                canonical_name: "size",
                aliases: &[],
                field_type: FieldType::Numeric,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Size",
                display_name: "Size",
                df_column: "size",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::SizeOnDisk => FieldMeta {
                id: self,
                canonical_name: "size_on_disk",
                aliases: &["sizeondisk", "size on disk", "allocated"],
                field_type: FieldType::Numeric,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "OnDisk",
                display_name: "Size on Disk",
                df_column: "allocated_size",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Created => FieldMeta {
                id: self,
                canonical_name: "created",
                aliases: &[],
                field_type: FieldType::Timestamp,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Created",
                display_name: "Created",
                df_column: "created",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Modified => FieldMeta {
                id: self,
                canonical_name: "modified",
                aliases: &["written", "date"],
                field_type: FieldType::Timestamp,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Modified",
                display_name: "Last Written",
                df_column: "modified",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Accessed => FieldMeta {
                id: self,
                canonical_name: "accessed",
                aliases: &[],
                field_type: FieldType::Timestamp,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Accessed",
                display_name: "Last Accessed",
                df_column: "accessed",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Extension => FieldMeta {
                id: self,
                canonical_name: "extension",
                aliases: &["ext"],
                field_type: FieldType::String,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Ascending),
                filterable: true,
                projectable: true,
                tui_label: "Ext",
                display_name: "Extension",
                df_column: "",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Medium,
                    default_top: 50,
                },
            },
            Self::Type => FieldMeta {
                id: self,
                canonical_name: "type",
                aliases: &["folder"],
                field_type: FieldType::Enum,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Ascending),
                filterable: true,
                projectable: true,
                tui_label: "Type",
                display_name: "Type",
                df_column: "type",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Low,
                    default_top: 30,
                },
            },
            Self::Attributes => FieldMeta {
                id: self,
                canonical_name: "attributes",
                aliases: &["attrs"],
                field_type: FieldType::Bitmask,
                access: FieldAccess::Derived,
                sortable: false,
                default_sort_direction: None,
                filterable: false,
                projectable: true,
                tui_label: "Attrs",
                display_name: "Attributes",
                df_column: "flags",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: false,
                    bucket_support: false,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::AttributeValue => FieldMeta {
                id: self,
                canonical_name: "attribute_value",
                aliases: &["attributevalue", "attrval"],
                field_type: FieldType::Bitmask,
                access: FieldAccess::Hot,
                sortable: false,
                default_sort_direction: None,
                filterable: true,
                projectable: true,
                tui_label: "AttrVal",
                display_name: "AttributeValue",
                df_column: "flags",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: false,
                    bucket_support: false,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Hidden => FieldMeta {
                id: self,
                canonical_name: "hidden",
                aliases: &["h"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "H",
                display_name: "Hidden",
                df_column: "is_hidden",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::System => FieldMeta {
                id: self,
                canonical_name: "system",
                aliases: &["s"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "S",
                display_name: "System",
                df_column: "is_system",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Archive => FieldMeta {
                id: self,
                canonical_name: "archive",
                aliases: &["a"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "A",
                display_name: "Archive",
                df_column: "is_archive",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::ReadOnly => FieldMeta {
                id: self,
                canonical_name: "read_only",
                aliases: &["readonly", "read-only", "read only", "r"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "R",
                display_name: "Read-only",
                df_column: "is_readonly",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Compressed => FieldMeta {
                id: self,
                canonical_name: "compressed",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "C",
                display_name: "Compressed",
                df_column: "is_compressed",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Encrypted => FieldMeta {
                id: self,
                canonical_name: "encrypted",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "E",
                display_name: "Encrypted",
                df_column: "is_encrypted",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Sparse => FieldMeta {
                id: self,
                canonical_name: "sparse",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Sp",
                display_name: "Sparse",
                df_column: "is_sparse",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Reparse => FieldMeta {
                id: self,
                canonical_name: "reparse",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Rp",
                display_name: "Reparse",
                df_column: "is_reparse",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Offline => FieldMeta {
                id: self,
                canonical_name: "offline",
                aliases: &["o"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "O",
                display_name: "Offline",
                df_column: "is_offline",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::NotIndexed => FieldMeta {
                id: self,
                canonical_name: "not_indexed",
                aliases: &[
                    "notindexed",
                    "not indexed",
                    "notcontent",
                    "not content indexed",
                    "not content indexed file",
                ],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "NI",
                display_name: "Not content indexed file",
                df_column: "is_not_indexed",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Temporary => FieldMeta {
                id: self,
                canonical_name: "temporary",
                aliases: &["temp"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "T",
                display_name: "Temporary",
                df_column: "is_temporary",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Virtual => FieldMeta {
                id: self,
                canonical_name: "virtual",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "V",
                display_name: "Virtual",
                df_column: "is_virtual",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Pinned => FieldMeta {
                id: self,
                canonical_name: "pinned",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Pin",
                display_name: "Pinned",
                df_column: "is_pinned",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Unpinned => FieldMeta {
                id: self,
                canonical_name: "unpinned",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Unp",
                display_name: "Unpinned",
                df_column: "is_unpinned",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::Descendants => FieldMeta {
                id: self,
                canonical_name: "descendants",
                aliases: &["decendents"],
                field_type: FieldType::Numeric,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Desc",
                display_name: "Descendants",
                df_column: "descendants",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::TreeSize => FieldMeta {
                id: self,
                canonical_name: "tree_size",
                aliases: &["treesize"],
                field_type: FieldType::Numeric,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "TreeSz",
                display_name: "Tree Size",
                df_column: "treesize",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::TreeAllocated => FieldMeta {
                id: self,
                canonical_name: "tree_allocated",
                aliases: &["treeallocated"],
                field_type: FieldType::Numeric,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "TreeAl",
                display_name: "Tree Allocated",
                df_column: "tree_allocated",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Bulkiness => FieldMeta {
                id: self,
                canonical_name: "bulkiness",
                aliases: &[],
                field_type: FieldType::Numeric,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Bulk",
                display_name: "Bulkiness",
                df_column: "bulkiness",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::Integrity => FieldMeta {
                id: self,
                canonical_name: "integrity",
                aliases: &[],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Int",
                display_name: "Integrity",
                df_column: "is_integrity_stream",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::NoScrub => FieldMeta {
                id: self,
                canonical_name: "no_scrub",
                aliases: &["noscrub", "no scrub", "no scrub file"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "NS",
                display_name: "No scrub file",
                df_column: "is_no_scrub_data",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::DirectoryFlag => FieldMeta {
                id: self,
                canonical_name: "directory_flag",
                aliases: &["directoryflag", "directory flag", "directory", "dir"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Dir?",
                display_name: "Directory Flag",
                df_column: "is_directory",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::RecallOnOpen => FieldMeta {
                id: self,
                canonical_name: "recall_on_open",
                aliases: &["recallonopen", "recall on open"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "RcO",
                display_name: "Recall on open",
                df_column: "is_recall_on_open",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::RecallOnDataAccess => FieldMeta {
                id: self,
                canonical_name: "recall_on_data_access",
                aliases: &["recallondataaccess", "recall on data access"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "RcD",
                display_name: "Recall on data access",
                df_column: "is_recall_on_data_access",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            Self::ParityAttributes => FieldMeta {
                id: self,
                canonical_name: "parity_attributes",
                aliases: &["parityattributes"],
                field_type: FieldType::Bitmask,
                access: FieldAccess::Derived,
                sortable: false,
                default_sort_direction: None,
                filterable: false,
                projectable: true,
                tui_label: "PAttr",
                display_name: "Attributes",
                df_column: "parity_flags",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: false,
                    bucket_support: false,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::NameLength => FieldMeta {
                id: self,
                canonical_name: "name_length",
                aliases: &["namelength", "name_len", "namelen"],
                field_type: FieldType::Numeric,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "NLen",
                display_name: "Name Length",
                df_column: "",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            Self::PathLength => FieldMeta {
                id: self,
                canonical_name: "path_length",
                aliases: &["pathlength", "path_len", "pathlen"],
                field_type: FieldType::Numeric,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "PLen",
                display_name: "Path Length",
                df_column: "",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: true,
                    groupable: false,
                    bucket_support: true,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
            // ── WI-4.4 forensic name-validity fields (opt-in, never default) ──
            // `malformed` is a hot-path bool computed against the lossless name
            // bytes (`name_bytes`), modelled on the `hidden`/`readonly` flags.
            Self::Malformed => FieldMeta {
                id: self,
                canonical_name: "malformed",
                aliases: &["ill_formed", "illformed", "bad_name"],
                field_type: FieldType::Bool,
                access: FieldAccess::Hot,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "Mal",
                display_name: "Malformed",
                df_column: "",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            // `malformed_path` is derived: it needs the resolved parent chain,
            // so it is evaluated post-filter (not compiled to the hot path).
            Self::MalformedPath => FieldMeta {
                id: self,
                canonical_name: "malformed_path",
                aliases: &["malformedpath", "ill_formed_path", "bad_path"],
                field_type: FieldType::Bool,
                access: FieldAccess::Derived,
                sortable: true,
                default_sort_direction: Some(SortDirection::Descending),
                filterable: true,
                projectable: true,
                tui_label: "MalP",
                display_name: "Malformed Path",
                df_column: "",
                default_value: "0",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: true,
                    bucket_support: false,
                    cardinality: Cardinality::Fixed,
                    default_top: 2,
                },
            },
            // `name_hex` is a projection-only string (the true name bytes as
            // hex); never filtered or sorted, never aggregated.
            Self::NameHex => FieldMeta {
                id: self,
                canonical_name: "name_hex",
                aliases: &["namehex", "name_bytes_hex"],
                field_type: FieldType::String,
                access: FieldAccess::Hot,
                sortable: false,
                default_sort_direction: None,
                filterable: false,
                projectable: true,
                tui_label: "Hex",
                display_name: "Name (hex)",
                df_column: "",
                default_value: "",
                aggregate: AggregateMeta {
                    aggregatable: false,
                    groupable: false,
                    bucket_support: false,
                    cardinality: Cardinality::Unbounded,
                    default_top: 0,
                },
            },
        }
    }
}
